language: php

php:
  - 7.1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-source

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls

sudo: false
